version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3311:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: XXXX
      MYSQL_ROOT_PASSWORD: XXXX
      MYSQL_USER: XXXX
      MYSQL_PASSWORD: XXX
    restart: always
  php:
    build: .
    ports:
      - 99:80
    volumes:
      - ./code:/var/www/html
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://XXXX
    ports:
      - 90:80
    restart: always
